type CommandName =
  | 'countWorkflows'
  | 'getClusterInfo'
  | 'getSearchAttributes'
  | 'getSystemInfo'
  | 'openBatchOperation'
  | 'openSchedule'
  | 'openSettings'
  | 'openWorkflow'
  | 'showTaskQueue'
  | 'startDevelopmentServer'
  | 'startWorkflow'
  | 'stopDevelopmentServer'
  | 'viewSchedules'
  | 'viewWorkflows';
